name: Workflow Step update and Welcome PR comment

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened]

permissions:
  contents: write      # Para ambos procesos
  pull-requests: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    # Solo se ejecuta para push y workflow_dispatch, no para pull_request
    if: github.event_name != 'pull_request'
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT

  on_start:
    name: On start
    needs: get_current_step
    if: >-
      ${{
        github.event_name != 'pull_request'
        && !github.event.repository.is_template
        && needs.get_current_step.outputs.current_step == 0
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Prepare a branch, and file
        run: |
          echo "Make sure we are on step 0"
          if [ "$(cat .github/steps/-step.txt)" != 0 ]; then
            echo "Current step is not 0"
            exit 0
          fi
          echo "Make a branch"
          BRANCH=welcome-workflow
          git checkout -b $BRANCH
          echo "Make a commit"
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git commit --allow-empty --message="Create an empty commit"
          echo "Push"
          git push --set-upstream origin $BRANCH
          echo "Restore main"
          git checkout main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update to step 1
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 0
          to_step: 1
          branch_name: welcome-workflow

  welcome_comment:
    name: Post welcome comment in PR
    runs-on: ubuntu-latest
    # Solo se ejecuta para pull_request
    if: github.event_name == 'pull_request'
    steps:
      - name: Add welcome comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Â¡Bienvenido/a! ðŸŽ‰ Gracias por crear tu primer Pull Request. Si tienes dudas, pregunta en los comentarios. Â¡Ã‰xitos!"
            })
